# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_r', models.IntegerField(primary_key=True, serialize=False)),
                ('name_r', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('EnUso', 'EnUso'), ('NoDisponible', 'NoDisponible'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=13)),
                ('date_c', models.DateField(verbose_name='date of creation')),
                ('date_m', models.DateField(verbose_name='date of modific')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_R', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACT', 'Activa'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='Activa', max_length=10)),
                ('_obs', models.CharField(max_length=100)),
                ('date_i', models.DateTimeField()),
                ('date_f', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TdRecurso',
            fields=[
                ('id_tdr', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30, verbose_name='state recurso type')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ladder', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='cin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.Usuario'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='recursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.Recurso'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='tdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.TdRecurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='id_tdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.TdRecurso'),
        ),
    ]
