# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_r', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del item')),
                ('name_r', models.CharField(max_length=30, verbose_name='Nombre del item')),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion del item')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('EnUso', 'EnUso'), ('NoDisponible', 'NoDisponible'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=13, verbose_name='Estado')),
                ('date_c', models.DateField(verbose_name='Fecha de submicion')),
                ('date_m', models.DateField(verbose_name='Fecha de alteracion')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_R', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACT', 'Activa'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='Activa', max_length=10)),
                ('obs', models.CharField(max_length=100)),
                ('date_i', models.DateTimeField()),
                ('date_f', models.DateTimeField()),
                ('recursos', models.ManyToManyField(to='polireserva.Recurso')),
            ],
        ),
        migrations.CreateModel(
            name='TdRecurso',
            fields=[
                ('id_tdr', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del Tipo de Recurso')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion del Tipo de Recurso')),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='tdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.TdRecurso'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurso',
            name='id_tdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.TdRecurso'),
        ),
    ]
