# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polireserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='recursos',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='tdr',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='date_c',
            field=models.DateField(verbose_name='Fecha de submicion'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='date_m',
            field=models.DateField(verbose_name='Fecha de alteracion'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripcion del item'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='id_r',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del item'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='name_r',
            field=models.CharField(max_length=30, verbose_name='Nombre del item'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('EnUso', 'EnUso'), ('NoDisponible', 'NoDisponible'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=13, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tdrecurso',
            name='description',
            field=models.CharField(max_length=30, verbose_name='Descripcion del Tipo de Recurso'),
        ),
        migrations.AlterField(
            model_name='tdrecurso',
            name='id_tdr',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del Tipo de Recurso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cin',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Nro de Cedula de Identidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ladder',
            field=models.CharField(max_length=20, verbose_name='Cargo del Usuario en la Institucion'),
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
