# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polireserva', '0002_auto_20170421_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_R', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACT', 'Activa'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='Activa', max_length=10)),
                ('_obs', models.CharField(max_length=100)),
                ('date_i', models.DateTimeField()),
                ('date_f', models.DateTimeField()),
                ('cin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.Usuario')),
                ('recursos', models.ManyToManyField(to='polireserva.Recurso')),
                ('tdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polireserva.TdRecurso')),
            ],
        ),
    ]
