# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polireserva', '0003_reservas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='_obs',
            new_name='obs',
        ),
    ]
