# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polireserva', '0004_auto_20170421_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='cin',
            new_name='user',
        ),
    ]
