# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(blank=True, max_length=10)),
                ('ladder', models.CharField(blank=True, choices=[(b'Usuario', b'Usuario normal'), (b'Tecnico', b'Tecnico del sistema'), (b'Recepcionista', b'Encargado de administrar reservas'), (b'Invitado', b'Invitado')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
