# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ladder',
            field=models.CharField(blank=True, choices=[(b'1', b'Invitado'), (b'2', b'Alumno'), (b'3', b'Auxiliar'), (b'4', b'Profesor'), (b'5', b'Director')], max_length=30),
        ),
    ]
